sudo: required
language: ruby
rvm:
  - 2.2.3
services:
  - docker
env:
  - NAME=${TRAVIS_REPO_SLUG:15} COMMIT=${TRAVIS_COMMIT:0:7}
before_install:
  - gem install bundler
  - bundle install
  - docker login -e="${HUB_EMAIL}" -u="${HUB_USERNAME}" -p="${HUB_PASSWORD}"
  - docker pull solinea/"${NAME}":latest || true
install:
  - docker build -t "${NAME}" .
before_deploy:
  - docker login -e="${DOCKER_EMAIL}" -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}"
    "${DOCKER_REGISTRY}"
  - docker login -e="${DOCKER_EMAIL}" -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}"
    "${DOCKER_REGISTRY_DEV}"
deploy:
  - provider: script
    script: build/bin/push-images-release
    on:
      tags: true
  - provider: script
    script: build/bin/push-images-master
    on:
      branch: master
notifications:
  email: false
  slack:
    secure: OARQQLvvSKtw7PAiKooi/pm11hQ452KNuunNmbSB19x+P6Z5y6+FqVA7BHymFMHJg5eNYHqRiLj8YSU3whtQQCOyz+hNE7LGZi4U48RSg+uDicLgeg2UV+/LsxtP01B6/ypGXG1En1UaKl+WGUQ11XrhVZQQZcJcUm40l7Zs2oVJMOoPs/9Q99jprl3J9yr3Ui72RNJJ2JXPLU8Ylp8HOnhDuVPRDbXM3qY98KFD84kN55zEPrbffcJ5theIptgMnmJWctXlonX1fyU7JBAvWZ0s44XMWq+ICxonfr43HrjgQ5RyRTzu6ax65GFDibVVqMy0x453S4Cq98IKloZZprpivGnZHhrCXBmu6sVZGz9hRZXZ9pU8pm+o9aoRpp7Zho/Y3d+GW7BAsCxo5jxwNAA7ho/RPEgIYPVJcT3vuiK4tpXhknB/Lnt4fbpGCt5CnVA/sw8CBt8Zl+BMRpr1uDh2CwNZxMwTzn6sdgSUXwZsXKKgIDVq/et9H4CijiRf7S2owlVpxCJ5PtA+u1VAFJ2ClVU5Ujgssf+65gEpvUwnaA3q5ADJPSIKnlfHIn5+nI5j68tvjvYR0QA1+mQ94SxGPNTTomLZN+DeAe8LYh4GqPyYezTxlIRod4ranBhAzEw4k8O55BxuvoJDa/bBZkgrO3qDAjMXYZWKNgvsQUI=
